language: node_js

node_js:
  - "5.2.0"

sudo: required

services:
  - docker
  - docker-compose

env:
  - TEST_DIR=server
  - COMPOSE_DIR=docker/compose

before_install:
  - npm install -g npm

before_script:
  - npm install -g grunt-cli

script:
  - cd $COMPOSE_DIR && docker-compose -f docker-compose.yml up
